### ISSUE TITLE
On Upgrading react native version to  0.60.5, app gets stuck on splash Screen

### ISSUE THREAD

**Issue by ParthShrivastav** [react-native-community/releases#139]
# Bug

## Environment info

React native info output:

```bash
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-4670S CPU @ 3.10GHz
    Memory: 909.61 MB / 7.91 GB
  Binaries:
    Node: 10.16.2 - C:\Program Files\nodejs\node.EXE
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156
```

## Steps To Reproduce

1. The application doesn't work in flow and gets stuck on the splash screen.
2. On changing the initial route of the application some screens works fine .
...

Describe what you expected to happen:

1. The application should work inflow and should not get stuck.
 

## Reproducible sample code

![Screenshot_1566196744](https://user-images.githubusercontent.com/51599211/63244126-2db2c500-c27a-11e9-8606-83f9d66acc3a.png)
It gets stuck here

![Screenshot_1566197074](https://user-images.githubusercontent.com/51599211/63244422-f5f84d00-c27a-11e9-8922-0a255a400602.png)
This individual screen in between of application works fine and flow works good, but it has issue after the splash screen.

**Comment by hackdie** [comment]
this is not the repo for reporting issues. go to the main repo and add more context if you want people to help you. Close this one
