### ISSUE TITLE
0.61.4

### ISSUE THREAD

**Issue by grabbou** [react-native-community/releases#151]
Conversations on this thread are limited to 0.61 releases major issues and backport (cherry-pick) requests from commits that are already on master.

An example of a good such request is a bug fix for a serious issue that has been merged into master but did not make the 0.61.4 cut.

In other words, if you cannot point to a particular commit on master, then your request likely belongs as a new issue in http://github.com/facebook/react-native/issues.

**Comment by thymikee** [comment]
- fix: Bundle assets in monorepo: https://github.com/facebook/react-native/commit/a3b08048674e324dbe1f0ca816f35607e9e06a2f

**Comment by pinstripe-potatohead** [comment]
Please cherry pick 
* Fix multiple `set-cookie` not aggregated correctly in response headers [@1df8bd4](https://github.com/facebook/react-native/commit/1df8bd4932f42958c01dccf44cee92b75a6988ed)

**Comment by grabbou** [comment]
@thymikee, at this point, the conclusion is that we will not be re-cutting 0.62. I am going to release its preview now and will cherry-pick that one in the next iteration.

**Comment by grabbou** [comment]
I am going to work on 0.62 right now and will get back to this issue in few days (later this week) and we will release another update.

**Comment by thymikee** [comment]
CLI bump: https://github.com/facebook/react-native/commit/e523302fbe055e6745e38b72a17e121341c431c1

**Comment by dnlowman** [comment]
> Please cherry pick
> 
>     * Fix multiple `set-cookie` not aggregated correctly in response headers [@1df8bd4](https://github.com/facebook/react-native/commit/1df8bd4932f42958c01dccf44cee92b75a6988ed)

Is this going to be backported? or is it scheduled for a later release? This is quite a big issue for us relying on cookies.

**Comment by niparx** [comment]
Add this, please: [Bump SoLoader to 0.8.0](https://github.com/facebook/react-native/commit/614039834bf255de096f8b1d168832f81b0cf3fa)

This fixes RN support for Android Bundle. See [here](https://github.com/facebook/react-native/issues/26400) for one of the issues. To be short: SoLoader can't find libraries, when app is installed to device from a Bundle

**Comment by radko93** [comment]
@niparx, unfortunately, this commit breaks 0.61.x branch so cannot be cherry-picked. But it's already there in RC 0.62.

**Comment by mikehardy** [comment]
@radko93 0.62-stable branch does not actually have an RC tag or package release yet but if I understand correctly it is buildable / green on CI with the exception of a regression to the need for the android gradle library pickFirst workaround returning (until fixed) 			
https://github.com/react-native-community/releases/issues/145 - which is to say, if I really needed app bundles *and* I was handy with doing an internal build/release of react-native (not easy, but not that hard) I might give 0.62-stable a whirl but otherwise it's not really available yet.

Not that it should be worked into 0.61.x or anything - just as information in case others are looking+waiting for that one

**Comment by grabbou** [comment]
Because 0.62 is going to wait for a few days, time to get back on this one and release fixes. Thank you @radko93 and @mikehardy for helping with the issues moderation! That is really appreciated!

**Comment by grabbou** [comment]
All commits cherry-picked. The release is on CircleCI and will be out soon.

**Comment by grabbou** [comment]
Closing as 0.61.5 is on CircleCI. Matter of ~30 minutes.
