### ISSUE TITLE
react-native-udp that is maintained by this community

### ISSUE THREAD

**Issue by gibo77** [react-native-community/releases#158]
# Feature Request

UDP is one of the most important communication for smart devices. React native is forefront of developing Smart Phones or Tablets. 
It would be prudent that this community should maintain **UDP communication.**

  Smart Phones are primarily used to control smart devices in our homes. UDP is very helpful in Universal Plug and Play UPnP or SSDP.

 Currently there is react-native-udp created by tradle. It is not maintained much and forking it to here would be better.

  The Smart Phone will send UDP multicast address for example 224.1.1.3 on port 1900. This multicast will have information for the any Smart devices in the LAN such as Home Automation. The Smart devices will pickup the UDP multicast and relay information back to the Smart Phone.
Fetch() works great but it is TCP. In TCP you can not send any data in LAN if you do not know the IP Address of the device.  In home automation most of the time you do not know the IP Address of the Smart Devices because the Wifi Router Dynamically change the IP Address sometimes. But you can program these Smart Devices to listen to certain multicast address such as 224.1.1.45 at Port 3333.

**Comment by kelset** [comment]
Hey there - this is the wrong repository to post this.

The correct one is the discussion&proposal repo, similar to what happened here -> https://github.com/react-native-community/discussions-and-proposals/issues/173 

It would also help if you could provide more info about the current maintainer and link the repo + link any issue where the current maintainer reported info about not wanting to maintain it anymore.

All of that said, there is an ongoing conversation about which packages belong in the org -> https://github.com/react-native-community/discussions-and-proposals/issues/176

Which has not got to a final decision, so probably the first step you should take about this could be for you to get the current maintainer to pass over to you the ownership of the repo.
