### ISSUE TITLE
[changelog-generator] Make it possible to use without a GH API token.

### ISSUE THREAD

**Issue by alloy** [react-native-community/releases#167]
# Feature Request

Make it possible to run the changelog-generator _without_ the need for a GitHub API authentication token.

## Why it is needed

Speaking with @kelset, I realized that e.g. the RNW people are wanting to be able to generate a changelog at any time and include internal changes. If they need that, there are probably others that need it too. These people most likely don’t need the GitHub handles of authors, so it could all be done locally.

@kmelmon Would you agree with this?

**Comment by alloy** [comment]
After discussing more with @TheSavior, the assumption is that this need will largely go away in v0.63.0, so we’ve agreed to do the sorting as a one off in the simplest way possible for just the v0.62.0 release.

**Comment by kmelmon** [comment]
I see this as a nice-to-have.  I don't think we'll see a large number of people needing to do this, so if this is difficult to implement, or exposes a real security issue, I think it would be fine to require the auth token.

**Comment by alloy** [comment]
Alright, not going to do this right now then.
