### ISSUE TITLE
"react-native": "^0.61.5" Crashes

### ISSUE THREAD

**Issue by uendar** [react-native-community/releases#170]
Hi everyone,

I am having an issue with the new version of react-native. I upgraded from 0.59.10 to 0.61.5., and when i run the project in debug mode i get crash. 
Hhere are the modules versions i use:

> "scripts": {
>     "android": "react-native run-android",
>     "ios": "react-native run-ios",
>     "start": "react-native start",
>     "test": "jest",
>     "lint": "eslint ."
>   },
>   "dependencies": {
>     "@react-native-community/netinfo": "^5.3.3",
>     "babel-preset-expo": "^5.0.0",
>     "base64-js": "^1.3.0",
>     "create-react-native-module": "^0.16.0",
>     "crypto-js": "^3.1.9-1",
>     "dateformat": "^3.0.3",
>     "formik": "^1.5.1",
>     "global": "^4.4.0",
>     "i18n-js": "^3.1.0",
>     "json2csv": "^4.3.3",
>     "lodash": "^4.17.15",
>     "mime": "^2.4.0",
>     "moment": "^2.23.0",
>     "native-base": "^2.13.7",
>     "prop-types": "^15.7.2",
>     "react": "16.9.0",
>     "react-native": "^0.61.5",
>     "react-native-action-button": "^2.7.0",
>     "react-native-charts-wrapper": "^0.5.7",
>     "react-native-document-picker": "^2.1.0",
>     "react-native-drawer": "^2.3.0",
>     "react-native-elements": "^1.1.0",
>     "react-native-exit-app": "^1.0.0",
>     "react-native-file-picker": "0.0.19",
>     "react-native-file-viewer": "^2.0.0",
>     "react-native-firebase": "^5.6.0",
>     "react-native-fs": "^2.15.2",
>     "react-native-gesture-handler": "^1.4.1",
>     "react-native-google-drive-api": "^1.0.22",
>     "react-native-google-drive-api-wrapper": "^1.1.22",
>     "react-native-google-signin": "^2.0.0",
>     "react-native-html-to-text": "0.0.5",
>     "react-native-image-crop-picker": "^0.21.3",
>     "react-native-image-picker": "^0.26.3",
>     "react-native-keyboard-aware-scroll-view": "^0.7.2",
>     "react-native-languages": "^3.0.2",
>     "react-native-linear-gradient": "^2.5.3",
>     "react-native-loading-spinner-overlay": "^0.5.2",
>     "react-native-modal": "^9.0.0",
>     "react-native-modal-datetime-picker": "^7.6.0",
>     "react-native-modal-filter-picker": "^1.3.4",
>     "react-native-onesignal": "^3.2.4",
>     "react-native-pdf": "^5.0.11",
>     "react-native-pie": "^0.4.0",
>     "react-native-popup-dialog": "^0.17.0",
>     "react-native-selectme": "^1.2.3",
>     "react-native-simple-radio-button": "^2.7.1",
>     "react-native-simple-toast": "0.0.8",
>     "react-native-smart-barcode": "^1.0.6",
>     "react-native-spinkit": "^1.4.1",
>     "react-native-step-indicator": "0.0.9",
>     "react-native-svg": "^9.3.1",
>     "react-native-tags": "^2.0.0",
>     "react-native-timeago": "^0.4.0",
>     "react-native-typography": "^1.4.0",
>     "react-native-vector-icons": "^6.2.0",
>     "react-navigation": "^3.8.1",
>     "react-navigation-redux-helpers": "^3.0.0",
>     "react-redux": "^5.0.1",
>     "realm": "^2.29.2",
>     "redux": "^4.0.0",
>     "redux-thunk": "^2.3.0",
>     "rn-fetch-blob": "^0.10.15",
>     "shortid": "^2.2.14",
>     "uuid": "^3.3.3",
>     "validate-model": "0.0.2",
>     "yup": "^0.26.10"
>   },
>   "devDependencies": {
>     "@babel/core": "^7.6.2",
>     "@babel/runtime": "^7.6.2",
>     "babel-jest": "^24.7.1",
>     "@react-native-community/eslint-config": "^0.0.5",
>     "babel-plugin-transform-property-literals": "^6.9.4",
>     "babel-preset-react-native": "4.0.1",
>     "schedule": "^0.4.0",
>     "jest": "^24.7.1",
>     "metro-react-native-babel-preset": "^0.56.0",
>     "react-test-renderer": "16.9.0",
>     "eslint": "^6.5.1"
>   },
>   "jest": {
>     "preset": "react-native",
>     "moduleFileExtensions": [
>       "js",
>       "json",
>       "es6",
>       "ios.js",
>       "android.js"
>     ]
>   },
>   "rnpm": {
>     "assets": [
>       "./assets/fonts/"
>     ]
>   }
> }

**Comment by lukebars** [comment]
Can you provide some sort of a crash log?

**Comment by uendar** [comment]
There is no crash log. This is what is strange to me

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. You should be posting this issue on the main [react native repo](https://github.com/facebook/react-native).
