### ISSUE TITLE
Broken link in releases tab

### ISSUE THREAD

**Issue by bell-steven** [react-native-community/releases#180]
# Bug

The blog post link in the [releases tab](https://github.com/facebook/react-native/releases/tag/v0.62.0) in the main repo is broken.  The correct link is `https://reactnative.dev/blog/2020/03/26/version-0.62` instead of `https://reactnative.dev/blog/2020/03/24/version-0.62`.  It is using the date the PR was created, but it seems like it was updated to today. 

Broken Link:
[https://reactnative.dev/blog/2020/03/24/version-0.62](https://reactnative.dev/blog/2020/03/24/version-0.62)

Working link:
[https://reactnative.dev/blog/2020/03/26/version-0.62](https://reactnative.dev/blog/2020/03/26/version-0.62)

## Environment info

N/A

`react-native info` output:

N/A

Library version: 0.62.0

I can't create a PR because it is in the releases tab.
The link is correct in CHANGELOG.md 

cc @alloy who created the release.

**Comment by bell-steven** [comment]
looks like its fixed. closing.

**Comment by alloy** [comment]
Thanks nonetheless for reporting!
