### ISSUE TITLE
 App is crashing on startup "RN Version 0.62.x"  on release variant 

### ISSUE THREAD

**Issue by naved971** [react-native-community/releases#193]
react-native run-android --variant=release

![image](https://user-images.githubusercontent.com/6028491/79579171-4f4da000-80d8-11ea-880d-7401973c0df4.png)

**Comment by tido64** [comment]
@naved971: Please report any issues with React Native here: https://github.com/facebook/react-native/issues/new/choose. This repo is for tracking releases.
