### ISSUE TITLE
0.62.2 Discussion

### ISSUE THREAD

**Issue by pvanny1124** [react-native-community/releases#196]
Hello, I am having this issue when trying to redirect back to the app after going through an oauth consent screen. I created an entirely new react native project and migrated code from 0.59.1.

<img width="421" alt="Screen Shot 2020-04-29 at 11 12 10 PM" src="https://user-images.githubusercontent.com/26369185/80668074-ddc60800-8a6e-11ea-8c19-44c03b14d304.png">

I have tried using `react-native clean-project-auto`, removing my `package-lock.json`, reinstalling `node_modules`, and nothing. Any help would be much appreciated!

System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 3.64 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.13.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 26.0.1, 27.0.3, 28.0.3
      System Images: android-22 | Google APIs Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-25 | Intel x86 Atom_64, android-25 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-27 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_191 - /usr/bin/javac
    Python: 2.7.15 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by sunnylqm** [comment]
You need to uninstall your previously installed app. AND this is not the place to ask questions, you should go to stackoverflow

**Comment by pvanny1124** [comment]
@sunnylqm cool, that worked. Thanks, Sunny. Sorry about that.
