### ISSUE TITLE
V0.X.0 Discussion

### ISSUE THREAD

**Issue by THNgit** [react-native-community/releases#210]
Conversations on this thread should be limited to reporting issues that are _new_ in this minor version or requests to cherry-pick bug fixes that _have_ landed in [master](https://github.com/facebook/react-native/commits/master).

In all other cases, please report the issue to http://github.com/facebook/react-native/issues.

**Comment by TheSavior** [comment]
Looks like this issue isn't tracking a release and may have been made as a mistake.
