### ISSUE TITLE
Why packaged react-native ships CameraRoll?

### ISSUE THREAD

**Issue by chrmod** [react-native-community/releases#213]
CameraRoll Library was removed from react-native core in https://github.com/facebook/react-native/commit/824d3a977057b336d81237ec3cec3a49a9d5e34d#diff-aeb428554a0acc6cc503a2e4da6ae61a that is July 2020.

Is it expected that it is still being part of v63 release cycle?

**Comment by chrmod** [comment]
Ok. I've found out that CameraRoll is still present of `63-stable` branch. So I assume it will go away in 64, right?

**Comment by kelset** [comment]
Yes, any commit you see currently in master will be in 0.64 since we have not cut yet the branch
