### ISSUE TITLE
Upcoming v0.64.1 cherrypicks discussion

### ISSUE THREAD

**Issue by grabbou** [react-native-community/releases#221]
Conversations on this thread are limited to 0.64 releases major issues and backport (cherry-pick) requests from commits that are already on master.

An example of a good such request is a bug fix for a serious issue that has been merged into master but did not make the 0.64.0 cut, with a link to the specific commit hash on master with the commit to cherry-pick, like this example link: https://github.com/facebook/react-native/commit/bd2b7d6c0366b5f19de56b71cb706a0af4b0be43

In other words, if you cannot point to a particular commit on master, then your request likely belongs as a new issue in http://github.com/facebook/react-native/issues.

**PRs to merge:**

- [ ] facebook/react-native#30637 
- [ ] facebook/react-native#31141
- [ ] https://github.com/facebook/react-native/pull/30027

**Ready for cherry-pick**:
- [x] (Security related fix): https://github.com/facebook/react-native/commit/33ef82ce6dfd31e1f990d438c925a0e52723e16b
- [ ] https://github.com/facebook/react-native/pull/30164 -> https://github.com/facebook/react-native/commit/00d9deaf6ba26c605694d303bb0cb072fceae5a1
- [ ] https://github.com/facebook/react-native/pull/31195 this was closed mentioning this as solution -> https://github.com/facebook/react-native/commit/bdfe2a51791046c4e6836576e08655431373ed67
- [ ] https://github.com/facebook/react-native/commit/310a6bcf4ba7ca162d3ba1c03e0ab07ff41f9ead
- [ ] https://github.com/facebook/react-native/commit/3399896ae756719b238e837001077a46508849be
- [ ] https://github.com/facebook/react-native/commit/0e9296b95da06789121f052e6cd6d7cac808464c
- [ ] https://github.com/facebook/react-native/commit/291cc95cc9e3c8e37fc7f2160d4eacd91b1c72be
- [ ] https://github.com/facebook/react-native/commit/36b58a824ea20daa22fe7c528a3bf0ff4e6a4cb5

**Issues to resolve:**
- [ ] https://github.com/facebook/react-native/issues/31245
- [ ] https://github.com/facebook/react-native/issues/31282
- [ ] https://github.com/facebook/react-native/issues/31149
- [x] https://github.com/facebook/react-native/issues/31179

---
*Edit by @kelset to update the status of PRs/commits/issues.*

**Comment by pvinis** [comment]
this should be there: https://github.com/react-native-community/cli/pull/1374

**Comment by TheSavior** [comment]
@grabbou, can you help make a list of all the PRs we need to merge that were already cherry picked into 0.64?

**Comment by hengkx** [comment]
```
react-native run-ios --configuration Release
```

warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'AlicloudUtils' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'boost-for-react-native' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'UMDevice' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 4.3, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'AlicloudPush' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'Bugly' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 4.3, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'AlicloudUT' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 6.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'UMCommon' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 4.3, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'AlicloudUTDID' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.4, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'Flipper-PeerTalk' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 6.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'libwebp' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 4.3, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'Toast' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'TOCropViewController-TOCropViewControllerBundle' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'RNImageCropPicker-QBImagePicker' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'GCDWebServer' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'Flipper-Glog' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 4.3, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'Base64' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'AliyunOSSiOS' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'YogaKit' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'TOCropViewController' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'SDWebImageWebPCoder' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 6.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'JWT' from project 'Pods')
warning: no rule to process file '/Users/tom/Documents/GitHub/media/ios/Pods/Flipper-RSocket/rsocket/benchmarks/CMakeLists.txt' of type 'text' for architecture 'x86_64' (in target 'Flipper-RSocket' from project 'Pods')
warning: no rule to process file '/Users/tom/Documents/GitHub/media/ios/Pods/Flipper-RSocket/rsocket/benchmarks/README.md' of type 'net.daringfireball.markdown' for architecture 'x86_64' (in target 'Flipper-RSocket' from project 'Pods')
warning: no rule to process file '/Users/tom/Documents/GitHub/media/ios/Pods/Flipper-RSocket/rsocket/README.md' of type 'net.daringfireball.markdown' for architecture 'x86_64' (in target 'Flipper-RSocket' from project 'Pods')
warning: no rule to process file '/Users/tom/Documents/GitHub/media/ios/Pods/Flipper-RSocket/rsocket/benchmarks/CMakeLists.txt' of type 'text' for architecture 'i386' (in target 'Flipper-RSocket' from project 'Pods')
warning: no rule to process file '/Users/tom/Documents/GitHub/media/ios/Pods/Flipper-RSocket/rsocket/benchmarks/README.md' of type 'net.daringfireball.markdown' for architecture 'i386' (in target 'Flipper-RSocket' from project 'Pods')
warning: no rule to process file '/Users/tom/Documents/GitHub/media/ios/Pods/Flipper-RSocket/rsocket/README.md' of type 'net.daringfireball.markdown' for architecture 'i386' (in target 'Flipper-RSocket' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'RNFastImage' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'react-native-video' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'react-native-oss' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'react-native-image-resizer' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'react-native-cookies' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'react-native-background-timer' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'RNShare' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'CodePush' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'RNImageCropPicker' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'react-native-static-server' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'react-native-splash-screen' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'react-native-keep-awake' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'react-native-blur' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'RNThumbnail' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'RNRate' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'RNImageMarker' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'RNFS' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'QrCode' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'BVLinearGradient' from project 'Pods')

** BUILD FAILED **


The following build commands failed:
        CompileSwift normal x86_64 /Users/tom/Documents/GitHub/media/node_modules/react-native-widgetkit/ios/Widgetkit.swift
        CompileSwiftSources normal i386 com.apple.xcode.tools.swift.compiler
        CompileSwift normal i386 /Users/tom/Documents/GitHub/media/node_modules/react-native-widgetkit/ios/Widgetkit.swift
(3 failures)

**Comment by hengkx** [comment]
![image](https://user-images.githubusercontent.com/8358236/111023301-30a07800-8413-11eb-922a-d773864da581.png)
0.63.4 is normal. What is the cause of 0.64.0? Thank you

**Comment by thymikee** [comment]
https://github.com/facebook/react-native/pull/30637 – making RN compatible with upcoming Jest 27, otherwise folks will need to use yarn `resolutions`

**Comment by kelset** [comment]
+1 on what @TheSavior says; I tried looking through the comments and I think this is the list, but please @grabbou verify it:
* https://github.com/facebook/react-native/pull/31128
* https://github.com/facebook/react-native/pull/30906
* https://github.com/facebook/react-native/pull/31027
(there were more I think but got merged in the meantime)

**Comment by kelset** [comment]
We should try to get this PR merged & cherry picked: https://github.com/facebook/react-native/pull/31141

**Comment by kelset** [comment]
worth considering too: https://github.com/facebook/react-native/commit/0e9296b95da06789121f052e6cd6d7cac808464c

**Comment by myckhel** [comment]
Please when will TurboModule be integrated?

**Comment by kelset** [comment]
@myckhel please refer to https://github.com/react-native-community/discussions-and-proposals/issues/40

**Comment by anchi20** [comment]
here, https://github.com/facebook/react-native/pull/29070

**Comment by tido64** [comment]
@anchi20: Please read the first post:

> Conversations on this thread are limited to 0.64 releases major issues and backport (cherry-pick) requests from commits that are _already on master_.

Please let us know when your PR has landed on master.

**Comment by Bardiamist** [comment]
Regression detected, font-family is not apply when secureTextEntry is true
Looks we need this PR again: https://github.com/facebook/react-native/pull/30164

Details:
https://github.com/facebook/react-native/issues/30123#issuecomment-802670151
`super.setTypeface(tf);` line at the wrong place again: https://github.com/facebook/react-native/blob/0.64-stable/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java#L423

**Comment by kelset** [comment]
Thanks for reporting @Bardiamist, looks like we need to cherry-pick again the commit from master: https://github.com/facebook/react-native/commit/00d9deaf6ba26c605694d303bb0cb072fceae5a1 (probably landed after 0.64 was cut)

**Comment by DanielMarkiel** [comment]
Hi,
I'm not sure if it's the correct discussion to bring this up, so I apologize in advance if not.

A bunch of people is facing the issue described here -> https://github.com/software-mansion/react-native-gesture-handler/issues/1284
In short, we all are getting the `java.lang.IllegalArgumentException: Unable to find JSIModule for class UIManager` error on Android from different packages after upgrading to RN 0.64.

1) Is this a known issue?
2) If not, is someone able to tell if this is something on the RN side, or it's some kind of incompatibility issue in each of mentioned packages with RN 0.64?

**Comment by grabbou** [comment]
> @grabbou, can you help make a list of all the PRs we need to merge that were already cherry picked into 0.64?

@TheSavior, here is the list of commits I have applied on 0.64-stable that were not merged to master at that time:
- https://github.com/facebook/react-native/pull/30978
- https://github.com/facebook/react-native/pull/31134
- https://github.com/facebook/react-native/pull/31128

**Comment by mikehardy** [comment]
@DanielMarkiel looks like that crash on Android for UIManager needs an issue in the react-native repo - I was not able to find anything that looked exactly on target for `Unable to find JSIModule for class UIManager` ([broad search attempted](https://github.com/facebook/react-native/issues?q=+Unable+to+find+JSIModule+for+class+UIManager)) though @Bardiamist was [active in a maybe-related issue](https://github.com/facebook/react-native/issues?q=+Unable+to+find+JSIModule+for+class+UIManager) - any issue opened is probably going to *really* need a minimal reproducible example to eliminate differences between hermes or not etc etc.

**Comment by Bardiamist** [comment]
`Unable to find JSIModule for class UIManager`

I created minimal reproducible example: https://github.com/facebook/react-native/issues/31245
I'm not sure where should be issue, but just in case I created on React native repo: https://github.com/facebook/react-native/issues/31245
Also I left link to minimal reproducible example on existing issue in `react-native-gesture-handler` repo: https://github.com/software-mansion/react-native-gesture-handler/issues/1284

**Comment by Johan-dutoit** [comment]
I believe there is a regression in the build script for iOS in 64, see: https://github.com/facebook/react-native/issues/31282

**Comment by mikehardy** [comment]
@Johan-dutoit more than one I think, `use_frameworks` is busted right now for iOS+RN64, no PR yet because it needs thought on where to put the spec generation step but there's a functioning workaround posted here https://github.com/facebook/react-native/issues/31149#issuecomment-800841668 and I put up a reproducible example.

**Comment by mayconline** [comment]
i'm problem with text input , when focusing on text input, it opens the keyboard the first time, but if you close the keyboard, and try to click on the text input again, the keyboard does not open again.

exists one issue open, but not resolution yet - https://github.com/facebook/react-native/issues/30746

**Comment by alexco2** [comment]
Hello,
Would it be possible to cherrypick this?
facebook/react-native#30737
This is a fix that would enable support for section list für the library react-native-collapsible-tab-view.

**Comment by mikehardy** [comment]
@alexco2 the commit hash is the important bit: https://github.com/facebook/react-native/commit/310a6bcf4ba7ca162d3ba1c03e0ab07ff41f9ead

**Comment by alexco2** [comment]
Thank you! I'm new to this whole process :)

**Comment by mikehardy** [comment]
If this is not already in the list, I think https://github.com/facebook/react-native/pull/31010 (update Flipper) is important, because Flipper was not published to mavenCentral until 0.75.x and jcenter is going away meaning builds will break by default with react-native 0.64 unless it's updated (or 0.65 is released) - commit https://github.com/facebook/react-native/commit/3399896ae756719b238e837001077a46508849be

**Comment by mikehardy** [comment]
This is just context but [I did a deep dive on "jcenter/bintray is going away"](https://github.com/react-native-device-info/react-native-device-info/pull/1220#issuecomment-822024898) to see if I could purge react-native-device-info module of jcenter uses - *including the example app* and it appears yoga's 'proguard-annotations' artifact is the key to it all. There are 3 items total

1- flipper itself (requested above)
2- flipper dependency on fbjni-android-only (fixed in flipper 0.79+, [so we actually need a newer one than is even on main dev branch](https://github.com/facebook/react-native/blob/2052bb63b5d6871562ff3c4adc4aac0475c575e2/template/android/gradle.properties#L28) but wait...)
3- [flipper dependency on yoga progaurd-annotations](https://github.com/facebook/flipper/blob/451c332260077ee991b08b948b4cc2e878254b79/build.gradle#L81) which is [still published on jcenter only](https://mvnrepository.com/artifact/com.facebook.yoga/proguard-annotations) but [tracked here](https://github.com/facebook/yoga/issues/1065) and will require a still-newer flipper unless they publish old artifacts on jitpack or mavenCentral

**Comment by kelset** [comment]
@mikehardy good info, would you mind also mentioning those here? https://github.com/react-native-community/discussions-and-proposals/issues/331

**Comment by stigi** [comment]
I'd like to nominate this PR that fixes dimensions after rotation on Android and that didn't make it into `0.64.0` yet:
- https://github.com/facebook/react-native/pull/30324

**Comment by kbrandwijk** [comment]
I would love to see this one make its way into 0.64.1, as there really is no good workaround: https://github.com/facebook/react-native/pull/30164 
A (low risk?) fix to Android fontstyling of placeholder texts for secureEntry TextInput fields.

**Comment by myckhel** [comment]
Please what are the plans for RN 0.64.1? 
Could it be the version of TurboModule support?

Can't really wait to have turbomodule enabled.

**Comment by pvinis** [comment]
This seems useful, as the issue happened with 64.0. https://github.com/facebook/react-native/pull/30027

**Comment by eliw00d** [comment]
> **PRs to merge:**
> 
> * [ ]  [facebook/react-native#31195](https://github.com/facebook/react-native/pull/31195)

This PR was closed in favor of https://github.com/facebook/react-native/commit/bdfe2a51791046c4e6836576e08655431373ed67. So, that should make it into 0.64.1, right?

**Comment by Ashoat** [comment]
Would be great to include https://github.com/facebook/react-native/commit/291cc95cc9e3c8e37fc7f2160d4eacd91b1c72be. Without this, Hermes crashes on Android don't log the error that causes the crash, which makes debugging really difficult. 

Additional context:
- Discussion in https://github.com/facebook/hermes/issues/439
- This commit was [previously requested](https://github.com/react-native-community/releases/issues/214#issuecomment-769296851) for 0.64.0 but unfortunately didn't make it

**Comment by kelset** [comment]
updated top post with the commits/issues/PRs mentioned so far. The Xcode 12.5 fix commit is still in the works so we'll have to wait for that before proceeding.

**Comment by TheSavior** [comment]
We need to get this security related fix into the next patch release for 0.64: https://github.com/facebook/react-native/commit/33ef82ce6dfd31e1f990d438c925a0e52723e16b

I'll add it to the list in the OP.

**Comment by robertying** [comment]
Could we have this PR https://github.com/facebook/react-native/pull/31062 looked at, merged and picked? It fixes Hermes build on Mac Catalyst.

**Comment by kelset** [comment]
Hey folks, we did a small patch release to address the Xcode 12.5 issue plus the security fix; so now we can go back to "standard" and discuss 0.64.2 over here -> https://github.com/react-native-community/releases/issues/224
