### ISSUE TITLE
Add to documentation info about the other parts of the toolchain we need to care

### ISSUE THREAD

**Issue by kelset** [react-native-community/releases#229]
We should have a dedicated document in the docs that is about the relationship between a React Native branch and the rest of the toolchain, in order to have clarity and know which things need to be kept up to date, aligned, etc.

Examples:
* Metro
* CLI
* Hermes
* Flipper
* Folly
* Gradle
* JSC
* react-native-codegen
* etc

Currently we only have tribal/incomplete knowledge and it's not ideal.

**Comment by grabbou** [comment]
This is a very good idea!

It would be great to document a typical errors that happen when e.g. certain dependencies are not up to date. For example, there are a few common issues that happen when you're on a different NDK version (we should add that one to the list too, btw) or when CodeGen dependency is off.

Would be happy to work towards documenting it, based on my past experience.

**Comment by lunaleaps** [comment]
I've started this doc -- more so in relation to releases -- https://github.com/react-native-community/releases/blob/master/docs/dependencies.md

**Comment by kelset** [comment]
Looks great! Thanks @lunaleaps

**Comment by kelset** [comment]
Closing off since we are deprecating the repo
