### ISSUE TITLE
Hermes Debugger not stopping on breakpoints 

### ISSUE THREAD

**Issue by lunaleaps** [react-native-community/releases#250]
### Version

0.66.0-rc.2

### Developer Environment

macOS, Intel, 

### Issue and Reproduction Steps

When attempting to set breakpoints in devtools they are not hitting but `debugger` statements do.

Steps to repro:
1. `npx react-native init --version 0.66.0-rc.2 MyTestProject662` and start metro `npm start` 
2. Follow [hermes debugging steps](https://reactnative.dev/docs/next/hermes#debugging-js-on-hermes-using-google-chromes-devtools) (but click on the React Native experimental target)
    ![](https://cdn.discordapp.com/attachments/514832743654228009/885951424184336394/dbuggingtarget.png)
3. Set a breakpoint via devtools in App.js and see if it hits

Expected:
* Should see debugger stop on line of breakpoint
Actual:
* Doesn't

Note: 
* Also reproduces on current release 0.65.1
* Happens on both Android and iOS

**Comment by fabriziobertoglio1987** [comment]
I made a quick investigation, but I don't know this part of the codebase. Sorry

```objc
- (BOOL)isRemoteDebuggingAvailable
{
  if (RCTTurboModuleEnabled()) {
    return NO;
  }
  Class jsDebuggingExecutorClass = objc_lookUpClass("RCTWebSocketExecutor");
  return (jsDebuggingExecutorClass != nil);
}
```

https://github.com/facebook/react-native/blob/f085e09be5a148065d286ba3950324dc9e44b7f6/React/CoreModules/RCTDevSettings.mm#L269-L276

https://github.com/facebook/react-native/commit/75f2da23c5d557862cf4b7bcdd8a1445b54d1c31

```java
  public void setRemoteJSDebugEnabled(final boolean isRemoteJSDebugEnabled) {
    if (!mIsDevSupportEnabled) {
      return;
    }


    UiThreadUtil.runOnUiThread(
        new Runnable() {
          @Override
          public void run() {
            mDevSettings.setRemoteJSDebugEnabled(isRemoteJSDebugEnabled);
            handleReloadJS();
          }
        });
  }
  ```
https://github.com/facebook/react-native/blob/ef6ad1f2d65639a1d41e05a895ad21ce97192749/ReactAndroid/src/main/java/com/facebook/react/devsupport/DevSupportManagerBase.java#L1033-L1046

**Comment by fkgozali** [comment]
@fabriziobertoglio1987 that code is for the old "Chrome debugging flow", not for Flipper debugger for Hermes

**Comment by nomi9995** [comment]
@lunaleaps I am using RN 64+ and Hermes. breakpoints are working perfectly on my side

**Comment by nomi9995** [comment]
@fkgozali can you add Hermes debugging in devsetting cmd+D instead of React Native Experiment inspect?

**Comment by kelset** [comment]
Closing off since we are deprecating the repo - if the problem persists please open an issue either in react-native core, or the hermes repo.
